### ISSUE TITLE
 Error: Unable to open socket

### ISSUE THREAD

**Issue by somedevreally** [StewartThomson/Gotify-Ext#23]
Hi,
on chrome browser, i was able to add local gotify server with token, after that if i click on browser icon, it says 
```
Error
Unable to open socket
```

**Comment by StewartThomson** [comment]
Hi there, did you configure the CORS headers & stream origins for your server, per the README?

**Comment by somedevreally** [comment]
oh i missed that part, i was so exicted i just went directly to chrome extension page lol..... . ok i added the environment in docker-compose.yml
```
environment:
            - GOTIFY_SERVER_RESPONSEHEADERS: "Access-Control-Allow-Methods: \"GET,POST,OPTIONS\"\nAccess-Control-Allow-Origin: \"chrome-extension://defcailckfpgaigaiijligpnjipkhhmg\"\nAccess-Control-Allow-Headers: \"Authorization, content-type\""
            - GOTIFY_SERVER_STREAM_ALLOWEDORIGINS: "- \"defcailckfpgaigaiijligpnjipkhhmg\""
```
and i get the error when i start the docker container
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.server.environment contains {"GOTIFY_SERVER_RESPONSEHEADERS": "Access-Control-Allow-Methods: \"GET,POST,OPTIONS\"\nAccess-Control-Allow-Origin: \"chrome-extension://defcailckfpgaigaiijligpnjipkhhmg\"\nAccess-Control-Allow-Headers: \"Authorization, content-type\""}, which is an invalid type, it should be a string
```

**Comment by StewartThomson** [comment]
Should work if you remove the dashes :)

See: https://stackoverflow.com/questions/43106459/environment-variable-assignment-in-docker-compose-colon-way

**Comment by somedevreally** [comment]
woah, removing dash helped, now the container up
also login with token did not worked, but login with user/pass worked.
thanks

**Comment by StewartThomson** [comment]
No problem! Hopefully, if this gets more users, I might see if the gotify maintainers are interested in hardcoding CORS acceptance of this extension. But we'll see
