### ISSUE TITLE
Differing UUIDs per extension installation in Firefox

### ISSUE THREAD

**Issue by Amolith** [StewartThomson/Gotify-Ext#44]
For Firefox, it looks like an extension's ID and its internal UUID differ for each installation.

Desktop (dark theme): `603715cf-f9f0-4157-8295-ede78487c3b6`
Laptop (light theme): `4ce66555-b17f-4c5f-8c99-b7ce6b2a59ea`
![image](https://user-images.githubusercontent.com/29460675/127259143-69c668e0-4d27-4601-b592-640000dc994e.png)
![image](https://user-images.githubusercontent.com/29460675/127259048-8bc2df8a-6b87-47f1-8637-7140427dc118.png)

Every extension I have installed on one of these devices has a different internal UUID from the other so it might be a good idea to indicate that in the README; users will either need to whitelist every installation or simply allow all origins.

**Comment by StewartThomson** [comment]
Hi, thank you for the issue.

That's interesting! They must have changed it at some point, because I swear I remember testing with the extension id, and it working.

I'll add a note to the README
